/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Sriram' at '1/1/17 10:08 PM' with Gradle 3.0
 *
 * @author Sriram, @date 1/1/17 10:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
